'use strict';
const $=id=>document.getElementById(id);
if(!window.L){$('status').textContent='Não foi possível carregar o Leaflet. Confira sua conexão e recarregue a página.';}else{
const mapa=L.map('mapa',{preferCanvas:true}).setView([-9.91,-63.04],10);
const bases={ruas:L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}),satelite:L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Tiles © Esri — Source: Esri, Maxar, Earthstar Geographics, and the GIS User Community'}),topografico:L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{maxNativeZoom:17,maxZoom:19,attribution:'Map data © OpenStreetMap contributors, SRTM | Map style © <a href="https://opentopomap.org">OpenTopoMap</a> (CC-BY-SA)'})};
bases.ruas.addTo(mapa);L.control.scale({imperial:false}).addTo(mapa);
for(const [nome,base]of Object.entries(bases)){base.on('tileerror',()=>{$('avisoTiles').textContent='Falha no carregamento do mapa base. Verifique a internet ou escolha outro fundo.';});base.on('load',()=>{$('avisoTiles').textContent='';});}
function setBase(nome){if(!bases[nome])return;Object.values(bases).forEach(b=>mapa.removeLayer(b));bases[nome].addTo(mapa);document.querySelectorAll('[data-base]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.base===nome)));}
document.querySelectorAll('[data-base]').forEach(b=>b.onclick=()=>setBase(b.dataset.base));
const config=[{id:'municipio',nome:'Limite municipal',arquivo:'Ariquemes_RO.geojson',cor:'#173d4c',peso:2.5,fill:0,pane:450},{id:'agua',nome:'Hidrografia',arquivo:'Hidrografia_Aiquemes.geojson',cor:'#008cdb',peso:2,fill:0,pane:430},{id:'imoveis',nome:'Imóveis declarados',arquivo:'imoveis_rurais_declarados_ariquemes_ro.geojson',cor:'#ae751b',peso:1,fill:.16,pane:410}];
const dados={},camadas={},opacidades={};let filtrados=[],selecionada=null;
const nf=new Intl.NumberFormat('pt-BR',{maximumFractionDigits:4});
function popup(f,nome){const box=document.createElement('div'),h=document.createElement('h3');h.textContent=f.properties.NORIOCOMP||f.properties.NM_MUN||f.properties.cod_imovel||nome;box.append(h);const table=document.createElement('table');table.className='attrs';for(const[k,v]of Object.entries(f.properties||{})){const row=table.insertRow();row.insertCell().textContent=k;row.insertCell().textContent=v==null?'Não informado':String(v);}box.append(table);return box;}
function selecionar(layer){if(selecionada){selecionada.camada.resetStyle(selecionada.layer);}const c=Object.values(camadas).find(c=>c.hasLayer(layer));if(!c)return;selecionada={layer,camada:c};layer.setStyle({color:'#007858',weight:4,fillColor:'#23ddbb',fillOpacity:.35});layer.openPopup();}
function criar(c,features){return L.geoJSON({type:'FeatureCollection',features},{pane:c.id,style:()=>({color:c.cor,weight:c.peso,opacity:opacidades[c.id],fillOpacity:c.fill*opacidades[c.id]}),onEachFeature:(f,layer)=>{layer.bindPopup(popup(f,c.nome),{maxWidth:370});layer.on('click',()=>selecionar(layer));}});}
function enquadrar(layer){const b=layer.getBounds();if(b.isValid())mapa.fitBounds(b,{padding:[25,25],maxZoom:16});}
function options(id,values){[...new Set(values.filter(v=>v!=null&&v!==''))].sort((a,b)=>String(a).localeCompare(String(b),'pt-BR')).forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;$(id).append(o);});}
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function aplicar(){if(!dados.imoveis)return;const min=$('min').value===''?null:Number($('min').value),max=$('max').value===''?null:Number($('max').value),q=norm($('busca').value.trim());if(min!==null&&max!==null&&min>max){$('contagem').textContent='A área mínima deve ser menor ou igual à máxima.';return;}filtrados=dados.imoveis.features.filter(f=>{const p=f.properties,a=Number(p.num_area);return(!q||norm(p.cod_imovel+' '+p.municipio).includes(q))&&(!$('situacao').value||p.des_condic===$('situacao').value)&&(!$('statusCadastro').value||p.ind_status===$('statusCadastro').value)&&(min===null||a>=min)&&(max===null||a<=max);});selecionada=null;camadas.imoveis.clearLayers();camadas.imoveis.addData({type:'FeatureCollection',features:filtrados});$('contagem').textContent=nf.format(filtrados.length)+' de '+nf.format(dados.imoveis.features.length)+' imóveis';$('resultados').replaceChildren();filtrados.slice(0,15).forEach(f=>{const b=document.createElement('button');b.className='result';b.textContent=f.properties.cod_imovel;b.onclick=()=>{camadas.imoveis.addTo(mapa);$('mostrar-imoveis').checked=true;camadas.imoveis.eachLayer(l=>{if(l.feature===f){enquadrar(l);selecionar(l);}});};$('resultados').append(b);});if(filtrados.length>15){const note=document.createElement('small');note.textContent='Lista: primeiros 15 resultados. O mapa e o download incluem todos os resultados.';$('resultados').append(note);}}
let debounce;for(const id of ['busca','situacao','statusCadastro','min','max'])$(id).addEventListener('input',()=>{clearTimeout(debounce);debounce=setTimeout(aplicar,200);});
$('limpar').onclick=()=>{for(const id of ['busca','situacao','statusCadastro','min','max'])$(id).value='';aplicar();};$('enquadrar').onclick=()=>{if(camadas.imoveis&&filtrados.length)enquadrar(camadas.imoveis);};$('inicio').onclick=()=>camadas.municipio&&enquadrar(camadas.municipio);
$('download').onclick=()=>{if(!dados.imoveis)return;const blob=new Blob([JSON.stringify({type:'FeatureCollection',features:filtrados})],{type:'application/geo+json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='imoveis_ariquemes_filtrados.geojson';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
$('localizarRio').onclick=()=>{if(!$('rio').value||!camadas.agua)return;const group=L.featureGroup();camadas.agua.eachLayer(l=>{if(l.feature.properties.NORIOCOMP===$('rio').value)group.addLayer(l);});camadas.agua.addTo(mapa);$('mostrar-agua').checked=true;enquadrar(group);};
$('tela').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.querySelector('main').requestFullscreen();}catch{$('avisoTiles').textContent='Este navegador não permite tela inteira.';}};document.addEventListener('fullscreenchange',()=>{setTimeout(()=>mapa.invalidateSize(),100);$('tela').textContent=document.fullscreenElement?'Sair da tela inteira':'Tela inteira';});$('imprimir').onclick=()=>window.print();mapa.on('mousemove',e=>{$('coord').textContent=`Latitude ${e.latlng.lat.toFixed(5)} · Longitude ${e.latlng.lng.toFixed(5)}`;});window.addEventListener('resize',()=>mapa.invalidateSize());
async function carregar(c){try{mapa.createPane(c.id).style.zIndex=c.pane;opacidades[c.id]=1;const r=await fetch('dados/'+c.arquivo);if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json();if(d.type!=='FeatureCollection'||!Array.isArray(d.features))throw Error('GeoJSON incompatível');dados[c.id]=d;camadas[c.id]=criar(c,d.features).addTo(mapa);const row=document.createElement('div');row.className='layer';const cb=document.createElement('input');cb.type='checkbox';cb.checked=true;cb.id='mostrar-'+c.id;const label=document.createElement('label');label.htmlFor=cb.id;label.textContent=c.nome+' ('+nf.format(d.features.length)+')';cb.onchange=()=>cb.checked?camadas[c.id].addTo(mapa):mapa.removeLayer(camadas[c.id]);const range=document.createElement('input');range.type='range';range.min=0;range.max=100;range.value=100;range.setAttribute('aria-label','Opacidade: '+c.nome);range.oninput=()=>{opacidades[c.id]=Number(range.value)/100;camadas[c.id].setStyle({opacity:opacidades[c.id],fillOpacity:c.fill*opacidades[c.id]});};const zoom=document.createElement('button');zoom.textContent='Ver';zoom.setAttribute('aria-label','Enquadrar '+c.nome);zoom.onclick=()=>enquadrar(camadas[c.id]);row.append(cb,label,range,zoom);$('camadas').append(row);if(c.id==='municipio')enquadrar(camadas[c.id]);if(c.id==='imoveis'){options('situacao',d.features.map(f=>f.properties.des_condic));options('statusCadastro',d.features.map(f=>f.properties.ind_status));aplicar();}if(c.id==='agua')options('rio',d.features.map(f=>f.properties.NORIOCOMP));return null;}catch(e){console.error(c.nome,e);return c.nome;}}
Promise.all(config.map(carregar)).then(errors=>{$('status').textContent=errors.filter(Boolean).length?'Não foi possível carregar: '+errors.filter(Boolean).join(', ')+'. Abra pelo servidor local; confira a pasta dados.':'3 camadas carregadas. Clique no mapa para consultar.';});
// Ferramentas opcionais para navegadores com suporte ao WebMCP.
if(navigator.modelContext&&typeof navigator.modelContext.registerTool==='function'){
 navigator.modelContext.registerTool({name:'definir_mapa_base',description:'Escolhe ruas, satelite ou topografico no geoportal.',inputSchema:{type:'object',properties:{base:{type:'string',enum:['ruas','satelite','topografico']}},required:['base']},execute:async({base})=>{setBase(base);return{content:[{type:'text',text:'Mapa base: '+base}]};}});
}
}
